#spring:
#  datasource:
#    url: jdbc:h2:mem:maindb
#    initialization-mode: always
#
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#
#    show-sql: true

spring:
  data:
    mongodb:
      port: 0 # when flapdoodle using
      database: company
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: info
    de.flapdoodle.os.common.attributes: warn
