spring:
  datasource:
    url: jdbc:h2:mem:maindb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

#spring:
#  datasource:
#    url: jdbc:h2:mem:maindb
#    initialization-mode: always
#  sql:
#    init:
##      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql
#
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#
#    show-sql: true
#    properties:
#      hibernate:
#      #format_sql: true
